### ISSUE TITLE
retrocycle() has a bug

### ISSUE THREAD

**Issue by bminer** [YChebotaev/json-decycle#1]
Consider this input:

```
{ tasks: 
   [ { type: 'task',
       description: 'Finish inbox',
       createdOn: '2017-11-07T22:02:19.696Z' },
     { type: 'task',
       description: 'Make sure it works',
       createdOn: '2017-11-07T22:02:36.775Z' } ],
  notes: 
   [ { type: 'note',
       content: 'This is a note',
       createdOn: '2017-11-07T22:02:27.631Z' },
     { type: 'note',
       content: 'It\'s working, I think.',
       createdOn: '2017-11-07T22:02:44.442Z' } ],
  inbox: 
   [ { '$ref': '#/tasks/0' },
     { '$ref': '#/notes/0' },
     { '$ref': '#/tasks/1' },
     { '$ref': '#/notes/1' } ],
}
```

This incorrect output is created when I run `JSON.parse(str, require("json-decycle").retrocycle() )`:

```
{ tasks: 
   [ { type: 'task',
       description: 'Finish inbox',
       createdOn: '2017-11-07T22:02:19.696Z' },
     { type: 'task',
       description: 'Make sure it works',
       createdOn: '2017-11-07T22:02:36.775Z' } ],
  notes: 
   [ { type: 'note',
       content: 'This is a note',
       createdOn: '2017-11-07T22:02:27.631Z' },
     { type: 'note',
       content: 'It\'s working, I think.',
       createdOn: '2017-11-07T22:02:44.442Z' } ],
  inbox: 
   [ { type: 'note',
       content: 'This is a note',
       createdOn: '2017-11-07T22:02:27.631Z' },
     { type: 'note',
       content: 'It\'s working, I think.',
       createdOn: '2017-11-07T22:02:44.442Z' },
     { '$ref': '#/tasks/1' },
     { '$ref': '#/notes/1' } ] }
```

Note that the `inbox` Object is not populated properly.  Some of the JSON references are not resolved, and some are incorrectly resolved.

Thoughts?

**Comment by HugoNaut90** [comment]
Unfortunatly i get the same bug. Did you find a solution so far?

**Comment by bminer** [comment]
@YChebotaev - If you need maintainers, I'd be happy to fix this bug and publish to NPM. I just need access to contribute to this repo and access to publish via NPM

**Comment by YChebotaev** [comment]
@bminer 👍 Thanks, I would love to see contributions for this lib. I added You as collaborator at github and npm.

**Comment by bminer** [comment]
Thanks. As soon as time permits, I'll take care of this bug. :)

**Comment by bminer** [comment]
@YChebotaev - I cannot seem to push to the repo. Are you sure that you added me as a collaborator?

**Comment by bminer** [comment]
Never mind!  I forgot to accept the invite.

**Comment by PieerePi** [comment]
@YChebotaev @bminer @HugoNaut90 

Hi, Guys!

I've fix this bug in https://github.com/YChebotaev/json-decycle/pull/5 , please have a review for me.

Thanks!

**Comment by YChebotaev** [comment]
@PieerePi That's awesome! Thanks! I will take closer look at weekends
