### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by maximilianMairinger** [YChebotaev/json-decycle#8]
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or locally?

**Comment by bminer** [comment]
I'm a TypeScript n00b, although I'm hoping to change that this year, haha!

Could you give me the 60-second elevator speech on what we'd need to do for TypeScript support?

Thanks!

**Comment by YChebotaev** [comment]
@bminer I feel like today TS is like sanity measure
