### ISSUE TITLE
Remove the one instance of nullish coalescing for compatibility

### ISSUE THREAD

**Issue by maximilianMairinger** [YChebotaev/json-decycle#9]
Nullish coalescing isn't supported in webpack@4 :/. More of a personal problem, but can't be bothered right now to update to webpack@5. 

https://github.com/YChebotaev/json-decycle/blob/76519d01ea923e5d018530dea91d83a57f0f5b35/index.js#L40

As there is only have one occurrence, we might as well change it in source. Another approach would be to locally implement a (simple) typescript building infrastructure as in #8 and add a target compiler option to a ES version <= 2019.

**Comment by maximilianMairinger** [comment]
Would be happy to help in both cases. Implementing #8 locally and in doing so fix this issue. If you give the ok @YChebotaev

**Comment by bminer** [comment]
I'm okay with this change. Seems pretty straightforward. Please submit a PR! Thanks!

**Comment by maximilianMairinger** [comment]
Solved in #10

**Comment by bminer** [comment]
I think we should close this for now.
https://caniuse.com/mdn-javascript_operators_nullish_coalescing
